spring:
    profiles:
        group:
            prod: prodDB, prodConfig, common
            test: testDB, devConfig, common
        active: prod
---
spring:
    config:
        activate:
            on-profile: prodConfig
---
spring:
    config:
        activate:
            on-profile: testDB
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testDB;MODE=MYSQL
        username: sa
---
spring:
    config:
        activate:
            on-profile: common

